service: serverless-monitoring

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - "sns:Publish"
      Resource:
        - ${self:custom.monitoring.topicArn}
  region: eu-west-2
  environment:
    url: ${opt:url}
    snsTopic: ${self:custom.monitoring.topicName}

functions:
  pinger-func:  
    handler: handler.ping
    events:
      - schedule:
          rate: rate(1 minute)
          enabled: true

plugins:
  - serverless-plugin-aws-alerts

custom:
  monitoring:
    topicName: monitoringTopic
    topicArn: 
      Fn::Join:
        - ":"
        - - arn
          - aws
          - sns
          - Ref: AWS::Region
          - Ref: AWS::AccountId
          - ${self:custom.monitoring.topicName}
  alerts:
    stages:
#       - dev
    topics:
      alarm:
        topic: ${self:custom.monitoring.topicName}
        notifications:
          - protocol: email
            endpoint: ${opt:email}

