service: serverless-monitoring

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - "sns:Publish"
        - "ses:SendEmail"
        - "ses:SendRawEmail"
      Resource:
        - ${self:custom.monitoring.topicArn}
        - ${self:custom.monitoring.toEmailIdentity}
        - ${self:custom.monitoring.fromEmailIdentity}
  # AWS SES only works in certain regions
  region: eu-west-1
  environment:
    url: ${opt:url}
    snsTopic: ${self:custom.monitoring.topicName}
    fromEmail: ${opt:fromEmail}
    toEmail: ${opt:toEmail}

functions:
  email-notify-function:
    handler: emailNotify.handler
    events: 
      - sns:
          topicName: ${self:custom.monitoring.topicName}
          displayName: ${self:custom.monitoring.topicName}
  pinger-function:
    handler: ping.handler
    events:
      - schedule:
          rate: rate(1 minute)
          enabled: true

plugins:
  - serverless-plugin-aws-alerts

custom:
  monitoring:
    arn: 
      Fn::Join:
        - ":"
        - - arn
          - aws
          - sns
          - Ref: AWS::Region
          - Ref: AWS::AccountId
    topicName: monitoringTopic
    topicArn: 
      Fn::Join:
        - ":"
        - - ${self:custom.monitoring.arn}
          - ${self:custom.monitoring.topicName}
    identity: 
      Fn::Join:
        - ":"
        - - arn
          - aws
          - ses
          - Ref: AWS::Region
          - Ref: AWS::AccountId
          - identity
    fromEmailIdentity: 
      Fn::Join:
        - "/"
        - - ${self:custom.monitoring.identity}
          - ${opt:fromEmail}
    toEmailIdentity: 
      Fn::Join:
        - "/"
        - - ${self:custom.monitoring.identity}
          - ${opt:toEmail}
  alerts:
    stages:
      - production
      - staging
      - dev
    topics:
      alarm: 
        topic: ${self:service}-dev-alerts-alarm
        notifications:
          - protocol: email
            endpoint: ${opt:toEmail}
    alarms:
      - functionErrors
      - functionThrottles

