service: serverless-monitoring2

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - "sns:Publish"
        - "ses:SendEmail"
        - "ses:SendRawEmail"
      Resource:
        - ${self:custom.monitoring.topicArn}
        - arn:aws:ses:eu-west-1:888455903372:identity/${opt:toEmail}
  region: eu-west-2
  environment:
    url: ${opt:url}
    snsTopic: ${self:custom.monitoring.topicName}
    fromEmail: ${opt:fromEmail}
    toEmail: ${opt:toEmail}

functions:
  email-notify-function:
    handler: emailNotify.handler
    events: 
      - sns:
          topicName: ${self:custom.monitoring.topicName}
          displayName: ${self:custom.monitoring.topicName}
  pinger-function:
    handler: ping.handler
    events:
      - schedule:
          rate: rate(1 minute)
          enabled: true

# plugins:
#   - serverless-plugin-aws-alerts

custom:
  monitoring:
    arn: 
      Fn::Join:
        - ":"
        - - arn
          - aws
          - sns
          - Ref: AWS::Region
          - Ref: AWS::AccountId
    topicName: monitoringTopic
    topicArn: 
      Fn::Join:
        - ":"
        - - ${self:custom.monitoring.arn}
          - ${self:custom.monitoring.topicName}
#   alerts:
#     stages:
# #       - dev
#     topics:
#       alarm:
#         topic: ${self:custom.monitoring.topicName}
#         notifications:
#           - protocol: email
#             endpoint: ${opt:email}

